name: amodeus_api
version: 0.1.0-alpha.2
description: Alternative MODEUS API client
homepage: https://amodeus.evgfilim1.me/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ">=4.0.0 <6.0.0"
  built_value: ^8.1.0
  built_collection: ^5.1.0

dev_dependencies:
  built_value_generator: ^8.1.0
  build_runner: any
  test: ^1.16.0
